<!DOCTYPE html>
<html lang="en-us">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 4.3.1">

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Nicholas Ollberding">

  
  
  
    
  
  <meta name="description" content="This post is also from the Introduction to Metagenomics Summer Workshop and provides a quick introduction to some common analytic methods used to analyze microbiome data. I thought it might be of interest to a broader audience so decided to post it here.

The goal of this session is to provide you with a high-level introduction to some common analytic methods used to analyze microbiome data. It will also serve to introduce you several popular R packages developed specifically for microbiome data analysis.">

  
  <link rel="alternate" hreflang="en-us" href="/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/">

  


  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/github.min.css" crossorigin="anonymous" title="hl-light">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" disabled>
        
      
    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin="anonymous">
    

    

  

  
  
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono&display=swap">
  

  
  
  
  <link rel="stylesheet" href="/css/academic.min.3bc694af15fd1e4ff7262e7dd46f11a8.css">

  

  
  
    <script>
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', 'UA-144821860-1', 'auto');
      
      ga('require', 'eventTracker');
      ga('require', 'outboundLinkTracker');
      ga('require', 'urlChangeTracker');
      ga('send', 'pageview');
    </script>
    <script async src="https://www.google-analytics.com/analytics.js"></script>
    
    <script async src="https://cdnjs.cloudflare.com/ajax/libs/autotrack/2.4.1/autotrack.js" integrity="sha512-HUmooslVKj4m6OBu0OgzjXXr+QuFYy/k7eLI5jdeEy/F4RSgMn6XRWRGkFi5IFaFgy7uFTkegp3Z0XnJf3Jq+g==" crossorigin="anonymous"></script>
    
  
  

  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/">

  
  
  
  
    
    
  
  <meta property="twitter:card" content="summary">
  
  <meta property="og:site_name" content="">
  <meta property="og:url" content="/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/">
  <meta property="og:title" content="Introduction to the Statistical Analysis of Microbiome Data in R | ">
  <meta property="og:description" content="This post is also from the Introduction to Metagenomics Summer Workshop and provides a quick introduction to some common analytic methods used to analyze microbiome data. I thought it might be of interest to a broader audience so decided to post it here.

The goal of this session is to provide you with a high-level introduction to some common analytic methods used to analyze microbiome data. It will also serve to introduce you several popular R packages developed specifically for microbiome data analysis."><meta property="og:image" content="/img/icon-192.png">
  <meta property="twitter:image" content="/img/icon-192.png"><meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2019-07-28T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2019-07-28T22:25:53-04:00">
  

  


  





  <title>Introduction to the Statistical Analysis of Microbiome Data in R | </title>

</head>

<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" >

  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


  
<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0 compensate-for-scrollbar" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="/"></a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav mr-auto">
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#about"><span>Home</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#posts"><span>Posts</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#projects"><span>Projects</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#talks"><span>Talks</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#featured"><span>Publications</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        

        <li class="nav-item">
          <a class="nav-link " href="/courses/"><span>Courses</span></a>
        </li>

        
        

        

        
        
        
          
        

        
        
        
        
        
        
          
          
          
            
          
          
        

        <li class="nav-item">
          <a class="nav-link " href="/#contact"><span>Contact</span></a>
        </li>

        
        

      
      </ul>
      <ul class="navbar-nav ml-auto">
      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


  <article class="article" itemscope itemtype="http://schema.org/Article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1 itemprop="name">Introduction to the Statistical Analysis of Microbiome Data in R</h1>

  

  
    



<meta content="2019-07-28 00:00:00 &#43;0000 UTC" itemprop="datePublished">
<meta content="2019-07-28 22:25:53 -0400 EDT" itemprop="dateModified">

<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    <time>Jul 28, 2019</time>
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    52 min read
  </span>
  

  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    <a href="/categories/microbiome/">Microbiome</a></span>
  

  
    
<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/&amp;text=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/&amp;t=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook-f"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R&amp;body=/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/&amp;title=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://web.whatsapp.com/send?text=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R%20/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/introduction-to-the-statistical-analysis-of-microbiome-data-in-r/&amp;title=Introduction%20to%20the%20Statistical%20Analysis%20of%20Microbiome%20Data%20in%20R" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>


  

</div>

    














  
</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<div id="section" class="section level1">
<h1></h1>
<p><br></p>
<p>This post is also from the <a href="https://github.com/Nick243/Introduction-to-Metagenomics-Summer-Workshop-2019">Introduction to Metagenomics Summer Workshop</a> and provides a quick introduction to some common analytic methods used to analyze microbiome data. I thought it might be of interest to a broader audience so decided to post it here.</p>
<p><br></p>
<p>The goal of this session is to provide you with a <strong>high-level introduction</strong> to some common analytic methods used to analyze microbiome data. It will also serve to introduce you several popular R packages developed specifically for microbiome data analysis. We chose to emphasize R for this course because of the rapid development of methods and packages provided in the R language, the breadth of existing tutorials and resources, and the ever expanding community of R users. However, other platforms such as <a href="https://qiime2.org/">QIIME2</a>, <a href="https://bitbucket.org/biobakery/biobakery/wiki/Home">biobakery</a> and <a href="https://www.drive5.com/usearch/">USEARCH</a>, just to name a few, offer <em>excellent integrated solutions</em> for the processing and analysis of amplicon and/or shotgun metagenomic sequence data.</p>
<p>The diverse goals and technical variation of metagenomic research projects does not allow for a standard <strong>“analytic pipeline”</strong> for microbiome data analysis. Approaching the analysis of microbiome data with a single workflow in mind is generally not a great idea, as there is no <em>“one size fits all”</em> solution for the assorted set of questions one might want to answer. However, you may be surprised to find that projects on very different topics often have overarching analytic aims such as:</p>
<ul>
<li>Describing the microbial community composition of a set of samples</li>
<li>Estimating within- and between-sample diversity</li>
<li>Identifying differentially abundant taxa</li>
<li>Predicting a response from a set of taxonomic features</li>
<li>Assessing microbial network structures and patterns of co-occurance</li>
<li>Exploring the phylogenetic relatedness of a set of organisms</li>
</ul>
<p>We will cover statistical methods developed to address several of these aims with a focus on introducing you to their implementation in R. A detailed description of each approach, its assumptions, package options, etc. is beyond the scope of this session. However, I try to provide links to source materials and more detailed documentation where possible. <strong>The statistical analysis of microbial metagenomic sequence data is a rapidly evolving field</strong> and different solutions (often many) have been proposed to answer the same questions. I have tried to focus on methods that are common in the microbiome literature, well-documented, and reasonably accessible…and a few I think are new and interesting. I also try to show a few different approaches in each section. In cases where I focus largely on more basic implementations, I have tried to provide links for advanced learning of more complex topics.</p>
<p><br></p>
<p>The publicly available data used in this session are from Giloteaux et. al. <a href="https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-016-0171-4">Reduced diversity and altered composition of the gut microbiome in individuals with myalgic encephalomyelitis/chronic fatigue syndrome</a> published in Microbiome (2016). The metadata, OTU table, and taxonomy files were obtained from the QIIME2 tutorial <a href="https://docs.qiime2.org/2019.4/tutorials/gneiss/">Differential abundance analysis with gneiss</a> (accessed on 06/13/2019). The code and data used to generate the phyloseq object is provided on my <a href="https://github.com/Nick243/Create-Giloteaux-2016-Phyloseq-Object">GitHub page</a>.
The data were generated by 16S rRNA gene sequencing (V4 hypervariable region) of fecal samples on the Illumina MiSeq. Our focus will be on examining differences in the microbiota of patients with chronic fatigue syndrome versus healthy controls. We will examine:</p>
<ul>
<li>Taxonomic relative abundance</li>
<li>Hierarchal clustering</li>
<li>Alpha-diversity</li>
<li>Beta-diversity</li>
<li>Differential abundance testing</li>
<li>Predicting class labels</li>
</ul>
<p><br></p>
</div>
<div id="additional-resources" class="section level1">
<h1>Additional resources</h1>
<p>There are many great resources for conducting microbiome data analysis in R. <a href="https://www.springer.com/gp/book/9789811315336">Statistical Analysis of Microbiome Data in R</a> by Xia, Sun, and Chen (2018) is an excellent textbook in this area. For those looking for an end-to-end workflow for amplicon data in R, I highly recommend Ben Callahan’s F1000 Research paper <a href="https://f1000research.com/articles/5-1492">Bioconductor Workflow for Microbiome Data Analysis: from raw reads to community analyses</a>. In addition there are numerous websites and vignettes dedicated to microbiome analyses. A few include:</p>
<ul>
<li>Paul McMurdie’s phyloseq <a href="https://joey711.github.io/phyloseq/">website</a></li>
<li>Robert Edgar’s <a href="https://www.drive5.com/usearch/manual/">website</a></li>
<li>The microbiome R package <a href="https://microbiome.github.io/microbiome/">website</a></li>
<li>All the materials and resources posted on the STAMPS <a href="https://github.com/mblstamps/stamps2018/wiki">wiki page</a> (a course I highly recommend!)</li>
</ul>
<p><br></p>
</div>
<div id="installing-packages" class="section level1">
<h1>Installing packages</h1>
<p>The code below will install the packages needed to run the analyses. These packages are installed from <a href="https://cran.r-project.org/">CRAN</a>, <a href="https://www.bioconductor.org/">Bioconductor</a> and from developer <a href="https://github.com/">GitHub</a> sites. Several of these packages are large, and have many dependencies, so this will take some time. This code was modified from Ben’s Bioconductor paper.</p>
<p>In general, package management and versioning can be a challenge for those new to R. Inevitably, if you do not take steps ahead of time, you will find that one of your programs that ran fine just a few months ago, no longer works! Often this is because changes in new versions of packages or R caused your code to break. There are multiple solutions depending on your goals, and all come with pros and cons, but a good place to start is to learn more about <a href="https://rstudio.github.io/packrat/">Packrat</a> and other package management tools.</p>
<p>If you already have many/some of these packages installed on your local system, you may want to skip this step and install manually only those that you need.</p>
<pre class="r"><code>.cran_packages &lt;- c(&quot;tidyverse&quot;, &quot;cowplot&quot;, &quot;picante&quot;, &quot;vegan&quot;, &quot;HMP&quot;, &quot;dendextend&quot;, &quot;rms&quot;, &quot;devtools&quot;)
.bioc_packages &lt;- c(&quot;phyloseq&quot;, &quot;DESeq2&quot;, &quot;microbiome&quot;, &quot;metagenomeSeq&quot;, &quot;ALDEx2&quot;)
.inst &lt;- .cran_packages %in% installed.packages()
if(any(!.inst)) {
  install.packages(.cran_packages[!.inst])
}
if (!requireNamespace(&quot;BiocManager&quot;, quietly = TRUE))
  install.packages(&quot;BiocManager&quot;)
BiocManager::install(.bioc_packages, version = &quot;3.9&quot;)
devtools::install_github(&quot;adw96/breakaway&quot;)
devtools::install_github(repo = &quot;UVic-omics/selbal&quot;)</code></pre>
<p><br></p>
</div>
<div id="loading-required-packages" class="section level1">
<h1>Loading required packages</h1>
<p>Let’s load the required packages. This is not the most elegant way to do this, but it allows you to see each package that is loaded and the version number.</p>
<pre class="r"><code>library(tidyverse); packageVersion(&quot;tidyverse&quot;)                 </code></pre>
<pre><code>## [1] &#39;1.2.1&#39;</code></pre>
<pre class="r"><code>library(phyloseq); packageVersion(&quot;phyloseq&quot;)                    </code></pre>
<pre><code>## [1] &#39;1.28.0&#39;</code></pre>
<pre class="r"><code>library(DESeq2); packageVersion(&quot;DESeq2&quot;)                        </code></pre>
<pre><code>## [1] &#39;1.24.0&#39;</code></pre>
<pre class="r"><code>library(microbiome); packageVersion(&quot;microbiome&quot;)               </code></pre>
<pre><code>## [1] &#39;1.6.0&#39;</code></pre>
<pre class="r"><code>library(vegan); packageVersion(&quot;vegan&quot;)                          </code></pre>
<pre><code>## [1] &#39;2.5.5&#39;</code></pre>
<pre class="r"><code>library(picante); packageVersion(&quot;picante&quot;)                       </code></pre>
<pre><code>## [1] &#39;1.8&#39;</code></pre>
<pre class="r"><code>library(ALDEx2); packageVersion(&quot;ALDEx2&quot;)                        </code></pre>
<pre><code>## [1] &#39;1.16.0&#39;</code></pre>
<pre class="r"><code>library(metagenomeSeq); packageVersion(&quot;metagenomeSeq&quot;)          </code></pre>
<pre><code>## [1] &#39;1.26.0&#39;</code></pre>
<pre class="r"><code>library(HMP); packageVersion(&quot;HMP&quot;)                              </code></pre>
<pre><code>## [1] &#39;1.6&#39;</code></pre>
<pre class="r"><code>library(dendextend); packageVersion(&quot;dendextend&quot;)                </code></pre>
<pre><code>## [1] &#39;1.12.0&#39;</code></pre>
<pre class="r"><code>library(selbal); packageVersion(&quot;selbal&quot;)                          </code></pre>
<pre><code>## [1] &#39;0.1.0&#39;</code></pre>
<pre class="r"><code>library(rms); packageVersion(&quot;rms&quot;)</code></pre>
<pre><code>## [1] &#39;5.1.3.1&#39;</code></pre>
<pre class="r"><code>library(breakaway); packageVersion(&quot;breakaway&quot;)                  </code></pre>
<pre><code>## [1] &#39;4.6.8&#39;</code></pre>
<p><br></p>
</div>
<div id="reading-in-the-giloteaux-data" class="section level1">
<h1>Reading in the Giloteaux data</h1>
<p>The data from the <strong>Giloteaux et. al. 2016 paper</strong> has been saved as a phyloseq object. We will use the readRDS() function to read it into R. We will also examine the distribution of read counts (per sample library size/read depth/total reads) and remove samples with &lt; 5k total reads. We will then create a new metadata field “Status” that provides more “descriptive” values for our primary variable of interest; whether or not the sample was from a patient with chronic fatigue syndrome or a healthy control.</p>
<p>This should all be familiar to those of you who worked through the <a href="https://github.com/Nick243/Introduction-to-Metagenomics-Summer-Workshop-2019">Introduction to Phyloseq</a> session. However, something that will be new is that now we are using pipes from the <a href="https://magrittr.tidyverse.org/">magrittr package</a> and <a href="https://www.tidyverse.org/">tidyverse</a> verbs to streamline some of the data manipulation steps. <em>For those of you have not worked with the tidyverse set of packages and functions you are missing out!</em> They will change they way you work in R. <a href="https://r4ds.had.co.nz/">R for Data Science</a> is an excellent source to learn more about the tidyverse packages and philosophy for data science.</p>
<p><strong>Additional quality controls checks and data pre-processing specific to the goals of your project should be conducted at this point (but is outside of the scope of the current session).</strong></p>
<pre class="r"><code>#Read in ps object
(ps &lt;- readRDS(&quot;C:/Users/olljt2/Desktop/academic_web_page/static/data/ps_giloteaux_2016.rds&quot;))</code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 138 taxa and 87 samples ]
## sample_data() Sample Data:       [ 87 samples by 22 sample variables ]
## tax_table()   Taxonomy Table:    [ 138 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 138 tips and 137 internal nodes ]
## refseq()      DNAStringSet:      [ 138 reference sequences ]</code></pre>
<pre class="r"><code>#Sort samples on total read count, remove &lt;5k reads, remove any OTUs seen in only those samples
sort(phyloseq::sample_sums(ps)) </code></pre>
<pre><code>## ERR1331827 ERR1331852 ERR1331856 ERR1331869 ERR1331833 ERR1331797 
##       2707       3031       3117       5083       5245       5307 
## ERR1331786 ERR1331818 ERR1331792 ERR1331803 ERR1331793 ERR1331819 
##       5696       5733       6463       6512       6622       6900 
## ERR1331858 ERR1331807 ERR1331815 ERR1331821 ERR1331843 ERR1331795 
##       6913       7121       7179       7272       7284       7314 
## ERR1331846 ERR1331811 ERR1331845 ERR1331842 ERR1331838 ERR1331855 
##       7569       7665       7815       7911       8102       8115 
## ERR1331824 ERR1331832 ERR1331804 ERR1331868 ERR1331831 ERR1331859 
##       8148       8186       8236       8612       8840       9016 
## ERR1331790 ERR1331789 ERR1331837 ERR1331857 ERR1331801 ERR1331841 
##       9085       9184       9731       9966      11173      11442 
## ERR1331861 ERR1331820 ERR1331854 ERR1331863 ERR1331806 ERR1331787 
##      11826      12940      13029      13094      13095      13690 
## ERR1331853 ERR1331851 ERR1331836 ERR1331835 ERR1331802 ERR1331799 
##      14113      14365      14488      14753      14799      14833 
## ERR1331847 ERR1331834 ERR1331817 ERR1331809 ERR1331828 ERR1331813 
##      15290      15367      15460      16162      16494      16749 
## ERR1331798 ERR1331816 ERR1331830 ERR1331785 ERR1331823 ERR1331865 
##      16947      17015      17457      17557      18506      19013 
## ERR1331848 ERR1331800 ERR1331867 ERR1331870 ERR1331810 ERR1331825 
##      19257      19443      19732      19783      19909      20069 
## ERR1331866 ERR1331871 ERR1331849 ERR1331860 ERR1331808 ERR1331872 
##      20760      20862      21540      21553      21713      22339 
## ERR1331812 ERR1331850 ERR1331791 ERR1331788 ERR1331796 ERR1331840 
##      22518      22639      23246      23751      23792      24752 
## ERR1331826 ERR1331822 ERR1331862 ERR1331864 ERR1331829 ERR1331844 
##      28186      28556      31064      44533      51918      57214 
## ERR1331805 ERR1331839 ERR1331794 
##      59355      61206      65941</code></pre>
<pre class="r"><code>(ps &lt;- phyloseq::subset_samples(ps, phyloseq::sample_sums(ps) &gt; 5000)) </code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 138 taxa and 84 samples ]
## sample_data() Sample Data:       [ 84 samples by 22 sample variables ]
## tax_table()   Taxonomy Table:    [ 138 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 138 tips and 137 internal nodes ]
## refseq()      DNAStringSet:      [ 138 reference sequences ]</code></pre>
<pre class="r"><code>(ps &lt;- phyloseq::prune_taxa(phyloseq::taxa_sums(ps) &gt; 0, ps)) </code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 138 taxa and 84 samples ]
## sample_data() Sample Data:       [ 84 samples by 22 sample variables ]
## tax_table()   Taxonomy Table:    [ 138 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 138 tips and 137 internal nodes ]
## refseq()      DNAStringSet:      [ 138 reference sequences ]</code></pre>
<pre class="r"><code>#Assign new sample metadata field
phyloseq::sample_data(ps)$Status &lt;- ifelse(phyloseq::sample_data(ps)$Subject == &quot;Patient&quot;, &quot;Chronic Fatigue&quot;, &quot;Control&quot;)
phyloseq::sample_data(ps)$Status &lt;- factor(phyloseq::sample_data(ps)$Status, levels = c(&quot;Control&quot;, &quot;Chronic Fatigue&quot;))
ps %&gt;% 
  sample_data %&gt;%
  dplyr::count(Status)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   Status              n
##   &lt;fct&gt;           &lt;int&gt;
## 1 Control            37
## 2 Chronic Fatigue    47</code></pre>
<p>We can see that we have a phyloseq object consisting of 138 taxa on 84 samples, 22 sample metadata fields, 7 taxonomic ranks and that a phylogenetic tree and the reference sequences have been included. We also see that there are data on n=37 controls and n=47 patients with chronic fatigue.</p>
<p><br></p>
</div>
<div id="visualizing-relative-abundance" class="section level1">
<h1>Visualizing relative abundance</h1>
<p>Often an early step in many microbiome projects to visualize the relative abundance of organisms at specific taxonomic ranks. Stacked bar plots and faceted box plots are two ways of doing this. I recommend that if using bar plots to include each sample as a separate observation (and not to aggregate by groups). This is because the sample-to-sample variability can be high, even within groups, which may be just or more important to observe than between-group differences…which can be obscured with aggregation.</p>
<p>The ability to discriminate between more than say a dozen colors in a single plot is also a limitation of the stacked bar plot (faceted box plots do not suffer this limitation). Thus, this is one analysis I often run in QIIME2 using the <a href="https://docs.qiime2.org/2019.4/tutorials/moving-pictures/">taxa barplot command</a>, as it allows for beautiful <a href="https://view.qiime2.org/visualization/?type=html&amp;src=https%3A%2F%2Fdocs.qiime2.org%2F2019.4%2Fdata%2Ftutorials%2Fmoving-pictures%2Ftaxa-bar-plots.qzv">interactive viewing</a>. This could also be done in R using a <a href="https://shiny.rstudio.com/">shiny app</a>. I just haven’t implemented, or seen others implement, this functionality yet in R (I imagine someone has so please let me know if/when you do).</p>
<p>Here we will agglomerate the reads to the phylum-level using phyloseq and plot the relative abundance by Status.</p>
<pre class="r"><code>#Get count of phyla
table(phyloseq::tax_table(ps)[, &quot;Phylum&quot;])</code></pre>
<pre><code>## 
##  Actinobacteria   Bacteroidetes   Cyanobacteria   Euryarchaeota 
##               7              11               2               1 
##      Firmicutes    Fusobacteria  Proteobacteria     Tenericutes 
##             105               1               7               2 
## Verrucomicrobia 
##               1</code></pre>
<pre class="r"><code>#Convert to relative abundance
ps_rel_abund = phyloseq::transform_sample_counts(ps, function(x){x / sum(x)})
phyloseq::otu_table(ps)[1:5, 1:5]</code></pre>
<pre><code>## OTU Table:          [5 taxa and 5 samples]
##                      taxa are rows
##      ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851
## OTU1          2        581        347        916      10498
## OTU2        371         46          0        233        301
## OTU3       1189         81        637        199          0
## OTU4          0        172        246          0        372
## OTU5        308         44        143        155        221</code></pre>
<pre class="r"><code>phyloseq::otu_table(ps_rel_abund)[1:5, 1:5]</code></pre>
<pre><code>## OTU Table:          [5 taxa and 5 samples]
##                      taxa are rows
##        ERR1331793  ERR1331872 ERR1331819  ERR1331794 ERR1331851
## OTU1 0.0003020236 0.026008326 0.05028986 0.013891206 0.73080404
## OTU2 0.0560253700 0.002059179 0.00000000 0.003533462 0.02095371
## OTU3 0.1795530051 0.003625946 0.09231884 0.003017849 0.00000000
## OTU4 0.0000000000 0.007699539 0.03565217 0.000000000 0.02589628
## OTU5 0.0465116279 0.001969649 0.02072464 0.002350586 0.01538462</code></pre>
<pre class="r"><code>#Plot
phyloseq::plot_bar(ps_rel_abund, fill = &quot;Phylum&quot;) +
  geom_bar(aes(color = Phylum, fill = Phylum), stat = &quot;identity&quot;, position = &quot;stack&quot;) +
  labs(x = &quot;&quot;, y = &quot;Relative Abundance\n&quot;) +
  facet_wrap(~ Status, scales = &quot;free&quot;) +
  theme(panel.background = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/bar%20plot-1.png" width="672" /></p>
<p>There are a total of nine phyla and their relative abundance looks to be quite simialr between groups. You could sort the taxa on abundance to improve the vizualization. I’ll let you give that a shot on your own. Let’s generate box plots according to group and facet them by phylum using the raw counts. We will use the phyloseq::melt function to help.</p>
<p><br></p>
<pre class="r"><code>#Agglomerate to phylum-level and rename
ps_phylum &lt;- phyloseq::tax_glom(ps, &quot;Phylum&quot;)
phyloseq::taxa_names(ps_phylum) &lt;- phyloseq::tax_table(ps_phylum)[, &quot;Phylum&quot;]
phyloseq::otu_table(ps_phylum)[1:5, 1:5]</code></pre>
<pre><code>## OTU Table:          [5 taxa and 5 samples]
##                      taxa are rows
##                ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851
## Bacteroidetes        1903        878       1837       1969      11776
## Proteobacteria        119       3315        468      62358        319
## Firmicutes           4319      14429       3548       1609       2207
## Actinobacteria         30        976         17          0         58
## Cyanobacteria         246          0          0          0          0</code></pre>
<pre class="r"><code>#Melt and plot
phyloseq::psmelt(ps_phylum) %&gt;%
ggplot(data = ., aes(x = Status, y = Abundance)) +
  geom_boxplot(outlier.shape  = NA) +
  geom_jitter(aes(color = OTU), height = 0, width = .2) +
  labs(x = &quot;&quot;, y = &quot;Abundance\n&quot;) +
  facet_wrap(~ OTU, scales = &quot;free&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/box%20plot-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>As we saw before, many samples have a high number of Firmicutes, followed by Bacteroidetes, and Actinobacteria. Most samples have low read counts for other phyla with some outlying samples. There does not appear to be much difference in the major phyla between groups. Check out Ben Callahan’s <a href="https://f1000research.com/articles/5-1492">F1000 paper</a> for additional examples on visualizing sequence variant prevalence/abundance that may be helpful for specific analyses.</p>
<p>One way to formally test for a difference in the phylum-level abundance is to conduct a multivariate test for differences in the overall composition between groups of samples. This type of test can be implemented using the <a href="https://cran.r-project.org/web/packages/HMP/index.html">HMP package</a> (Xdc.sevsample function) described in the paper <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0052078">Hypothesis Testing and Power Calculations for Taxonomic-Based Human Microbiome Data</a> by La Rosa et. al.</p>
<p>Basically, a <a href="https://en.wikipedia.org/wiki/Dirichlet-multinomial_distribution">Dirichlet-Multinomial distribution</a> is assumed for the data and null hypothesis testing is conducted by testing for a difference in the location (mean distribution of each taxa) across groups accounting for the overdispersion in the count data. The authors describe this test as analogous to a two sample t-test, but instead we are evaluating whether taxa frequencies observed in both groups of metagenomic samples are equal (null hypothesis). Here we are performing the test on bacterial phyla, but it could be performed <strong>at any taxonomic level</strong> including OTUs. The authors recommend that rare taxa be pooled into a single group to improve testing.</p>
<pre class="r"><code>#Subset groups
controls &lt;- phyloseq::subset_samples(ps_phylum, Status == &quot;Control&quot;)
cf &lt;- phyloseq::subset_samples(ps_phylum, Status == &quot;Chronic Fatigue&quot;)
#Output OTU tables
control_otu &lt;- data.frame(phyloseq::otu_table(controls))
cf_otu &lt;- data.frame(phyloseq::otu_table(cf))
#Group rare phyla
control_otu &lt;- control_otu %&gt;%
  t(.) %&gt;%
  as.data.frame(.) %&gt;%
  mutate(Other = Cyanobacteria + Euryarchaeota + Tenericutes + Verrucomicrobia + Fusobacteria) %&gt;%
  dplyr::select(-Cyanobacteria, -Euryarchaeota, -Tenericutes, -Verrucomicrobia, -Fusobacteria)
cf_otu &lt;- cf_otu %&gt;%
  t(.) %&gt;%
  as.data.frame(.) %&gt;%
  mutate(Other = Cyanobacteria + Euryarchaeota + Tenericutes + Verrucomicrobia + Fusobacteria) %&gt;%
  dplyr::select(-Cyanobacteria, -Euryarchaeota, -Tenericutes, -Verrucomicrobia, -Fusobacteria)
#HMP test
group_data &lt;- list(control_otu, cf_otu)
(xdc &lt;- HMP::Xdc.sevsample(group_data))           </code></pre>
<pre><code>## $`Xdc statistics`
## [1] 0.2769004
## 
## $`p value`
## [1] 0.9980551</code></pre>
<pre class="r"><code>1 - pchisq(.2769004, 5)</code></pre>
<pre><code>## [1] 0.9980551</code></pre>
<p>The HMP test fails to reject the null hypothesis of no difference in the distribution of phyla between groups (in line with our expectations). The xdc test follows a Chi-square distribution with degrees of freedom equal to (J-1)*K, where J is the number of groups and K is the number of taxa. The last calculation just shows how the p-value is obtained. The test can be expanded to more than two groups and to test for differences in rank abundance distributions (RAD). These are topics I encourage you to explore on your own.
The microbiome package also has some nice functions for visualizing <a href="http://microbiome.github.io/microbiome/Composition.html">community composition</a> you should look into.</p>
<p><br></p>
</div>
<div id="hierarchical-clustering" class="section level1">
<h1>Hierarchical clustering</h1>
<p>Another early step in many microbiome projects to examine how samples cluster on some measure of taxonomic (dis)similarity. There are <strong>MANY</strong> ways to do perform such clustering. Here I present just one approach that I assume many of you are familiar with. We will perform hierarchal clustering of samples based on their Bray-Curtis dissimilarity. Here is a link to how it is <a href="https://en.wikipedia.org/wiki/Bray%E2%80%93Curtis_dissimilarity">calculated</a>. We will discuss this in more detail during the lecture, but for now it should suffice to know that the <strong>as two samples share fewer taxa, the number increases.</strong> The Bray-Curtis dissimilarity is zero for samples that have the exact same composition and one for those sharing no taxa. It is also worth remembering that this is a measure of dissimilarity (it is not a true distance measure).</p>
<p>We will use the popular <a href="https://www.rdocumentation.org/packages/vegan/versions/2.4-2">vegan package</a> for community ecology to compute the Bray-Curtis dissimilarity for all samples. Then we will apply Ward’s clustering and color code the sample names to assess the extent to which the samples from the control and chronic fatigue participants cluster. At a high-level, Ward’s clustering finds the pair of clusters at each iteration that minimalizes the increase in total variance.</p>
<p>Let’s see how this is done in R.</p>
<pre class="r"><code>#Extract OTU table and compute BC
ps_rel_otu &lt;- data.frame(phyloseq::otu_table(ps_rel_abund))
ps_rel_otu &lt;- t(ps_rel_otu)
bc_dist &lt;- vegan::vegdist(ps_rel_otu, method = &quot;bray&quot;)
as.matrix(bc_dist)[1:5, 1:5]</code></pre>
<pre><code>##            ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851
## ERR1331793  0.0000000  0.8801040  0.5975550  0.9767218  0.8684629
## ERR1331872  0.8801040  0.0000000  0.7590766  0.9596181  0.9206484
## ERR1331819  0.5975550  0.7590766  0.0000000  0.9556656  0.7810736
## ERR1331794  0.9767218  0.9596181  0.9556656  0.0000000  0.9693291
## ERR1331851  0.8684629  0.9206484  0.7810736  0.9693291  0.0000000</code></pre>
<pre class="r"><code>#Save as dendrogram
ward &lt;- as.dendrogram(hclust(bc_dist, method = &quot;ward.D2&quot;))
#Provide color codes
meta &lt;- data.frame(phyloseq::sample_data(ps_rel_abund))
colorCode &lt;- c(Control = &quot;red&quot;, `Chronic Fatigue` = &quot;blue&quot;)
labels_colors(ward) &lt;- colorCode[meta$Status][order.dendrogram(ward)]
#Plot
plot(ward)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/wards-1.png" width="1536" style="display: block; margin: auto;" /></p>
<p>We can see that the Bray-Curtis dissimilarity for these selected samples range from around 0.6 to close to 1. Thus, the composition of some samples are quite different from one another. We also see some clustering according to Status near the tips, but no clear “higher-level” clustering. We will try to exploit this information later to see if we can predict the label of each sample with only information on the microbial relative abundances.</p>
<p>Heatmaps are another good way to visualize these types of associations and can be implemented using <a href="https://joey711.github.io/phyloseq/plot_heatmap-examples.html">phyloseq</a>. Give it a try on your own!</p>
<p><br></p>
</div>
<div id="alpha-diversity" class="section level1">
<h1>Alpha-diversity</h1>
<p>Robert Edgar provides an excellent definition of alpha-diversity on his <a href="https://www.drive5.com/usearch/manual/alpha_diversity.html">website</a>:</p>
<blockquote>
<p>Alpha-diversity is the diversity in a single ecosystem or sample. The simplest measure is richness, the number of species (or OTUs) observed in the sample. Other metrics consider the abundances (frequencies) of the OTUs, for example to give lower weight to lower-abundance OTUs.</p>
</blockquote>
<p>Basically, it is the within-sample diversity and includes how many organisms are observed (i.e. observed OTUs) and how evenly they are distributed. Many researchers are interested in estimating alpha-diversity since differences between groups have been associated with several health related outcomes. <strong>However the issue of how to best estimate these quantities using data derived from next-generation sequencing (NGS) is controversial.</strong> This is due to two main reasons:</p>
<ol style="list-style-type: decimal">
<li>The observed richness in a sample/site is typically underestimated due to inexhaustive sampling. Thus, valid estimators of diversity require extrapolating from the available observations to provide estimates of the unobserved taxa (and also account for the sampling variability).</li>
<li>Extrapolation estimators require an accurate count of the rare taxa (including singletons) in each sample…which for NGS-based metagenomics studies we typically do not have…since singletons generally cannot be differentiated from sequencing errors using the current best informatics workflows. The extent to which we cannot accurately detect low abundance taxa limits the utility of diversity estimators reliant upon such counts.</li>
</ol>
<p><em>So we are kind of in a catch-22 regarding the best way forward given current technologies.</em></p>
<p>It has been argued; however, that diversity metrics can nevertheless be compared between samples because the errors and biases <strong>are mostly systematic</strong> (i.e. occur with similar rates in all samples). See Dr. Edgar’s discussion of the topic <a href="https://www.drive5.com/usearch/manual/diversity_metrics_compare_groups.html">here</a> for more detail. This is what is typically done in most published studies to date. A major underlying assumption here is that abundance structures are the same for the two groups being compared. This is perhaps a reasonable assumption when comparing similar environments, but it is hard to know without exhaustive sampling. See figure 1 <a href="https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231878.full.pdf">here</a> and the related discussion by Amy Willis for a more detailed understanding of how the abundance structure can lead you to incorrect conclusions (quite disconcerting).</p>
<p>Rarefaction (subsampling reads from each sample without replacement to a constant depth) is often performed before estimating alpha-diversity; although, it is unclear to me if/when this helps since <em>environments can be identical with respect to one alpha diversity metric, but the different abundance structures will induce different biases when rarified</em> (italicized text taken from Amy’s paper linked to above).</p>
<p>Dr. Willis has examined this issue in depth and developed <a href="https://github.com/adw96/breakaway">breakaway</a> and <a href="https://github.com/adw96/DivNet">DivNet</a> to specifically address the shortcoming of current approaches. I highly recommend you check out her <a href="https://github.com/adw96">GitHub site</a>. In a recent <a href="https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231878.full.pdf">paper</a> she argues:</p>
<blockquote>
<p>In order to draw meaningful conclusions about the entire microbial community, it is necessary to adjust for inexhaustive sampling using statistically-motivated parameter estimates for alpha diversity. In order to draw meaningful conclusions regarding comparisons of microbial communities, it is necessary to use measurement error models to adjust for the uncertainty in the estimation of alpha diversity.
She also states that breakaway is not <em>overly sensitive</em> to singleton counts.</p>
</blockquote>
<p>The links below provide a brief introduction to the topic. I look forward to Amy’s updated tutorial and thoughts on when microbial diversity estimation is, and isn’t, possible as mentioned in the last link <em>(I suspect it will result in some updating of these materials)</em>.</p>
<ul>
<li><a href="https://www.drive5.com/usearch/manual/alpha_diversity.html" class="uri">https://www.drive5.com/usearch/manual/alpha_diversity.html</a></li>
<li><a href="https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231878.full.pdf" class="uri">https://www.biorxiv.org/content/biorxiv/early/2017/12/11/231878.full.pdf</a></li>
<li><a href="https://github.com/benjjneb/dada2/issues/103" class="uri">https://github.com/benjjneb/dada2/issues/103</a></li>
<li><a href="https://github.com/benjjneb/dada2/issues/317" class="uri">https://github.com/benjjneb/dada2/issues/317</a></li>
</ul>
<p><br></p>
<p>Below we will estimate and test for differences according to chronic fatigue status using the plug-in estimates for observed richness, Shannon diversity, and phylogenetic diversity on the subsampled data (since this is common practice). I have also provided some code to estimate richness using breakaway that you can examine on your own. I plan to update this section with some data that is more appropriate for breakaway. So check back soon.</p>
<pre class="r"><code>ggplot(data = data.frame(&quot;total_reads&quot; =  phyloseq::sample_sums(ps),
                         &quot;observed&quot; = phyloseq::estimate_richness(ps, measures = &quot;Observed&quot;)[, 1]),
       aes(x = total_reads, y = observed)) +
  geom_point() +
  geom_smooth(method=&quot;lm&quot;, se = FALSE) +
  labs(x = &quot;\nTotal Reads&quot;, y = &quot;Observed Richness\n&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/read%20plot-1.png" width="672" /></p>
<p><br></p>
<p>We see that the observed OTUs are correlated with the total read count (as expected). Now let’s subsample, plot, and test for group differences.</p>
<pre class="r"><code>#Subsample reads
(ps_rare &lt;- phyloseq::rarefy_even_depth(ps, rngseed = 123, replace = FALSE))             </code></pre>
<pre><code>## `set.seed(123)` was used to initialize repeatable random subsampling.</code></pre>
<pre><code>## Please record this for your records so others can reproduce.</code></pre>
<pre><code>## Try `set.seed(123); .Random.seed` for the full vector</code></pre>
<pre><code>## ...</code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 138 taxa and 84 samples ]
## sample_data() Sample Data:       [ 84 samples by 23 sample variables ]
## tax_table()   Taxonomy Table:    [ 138 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 138 tips and 137 internal nodes ]
## refseq()      DNAStringSet:      [ 138 reference sequences ]</code></pre>
<pre class="r"><code>head(phyloseq::sample_sums(ps_rare))</code></pre>
<pre><code>## ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851 ERR1331834 
##       5083       5083       5083       5083       5083       5083</code></pre>
<pre class="r"><code>#Generate a data.frame with adiv measures
adiv &lt;- data.frame(
  &quot;Observed&quot; = phyloseq::estimate_richness(ps_rare, measures = &quot;Observed&quot;),
  &quot;Shannon&quot; = phyloseq::estimate_richness(ps_rare, measures = &quot;Shannon&quot;),
  &quot;PD&quot; = picante::pd(samp = data.frame(t(data.frame(phyloseq::otu_table(ps_rare)))), tree = phyloseq::phy_tree(ps_rare))[, 1],
  &quot;Status&quot; = phyloseq::sample_data(ps_rare)$Status)
head(adiv)</code></pre>
<pre><code>##            Observed   Shannon        PD          Status
## ERR1331793       53 2.7462377 20.597980 Chronic Fatigue
## ERR1331872       52 2.7527053 21.289719         Control
## ERR1331819       70 3.2378006 21.671340         Control
## ERR1331794       27 0.3761523  8.275154 Chronic Fatigue
## ERR1331851       45 1.3387308 14.783592 Chronic Fatigue
## ERR1331834       54 2.8883445 20.988640         Control</code></pre>
<pre class="r"><code>#Plot adiv measures
adiv %&gt;%
  gather(key = metric, value = value, c(&quot;Observed&quot;, &quot;Shannon&quot;, &quot;PD&quot;)) %&gt;%
  mutate(metric = factor(metric, levels = c(&quot;Observed&quot;, &quot;Shannon&quot;, &quot;PD&quot;))) %&gt;%
  ggplot(aes(x = Status, y = value)) +
  geom_boxplot(outlier.color = NA) +
  geom_jitter(aes(color = Status), height = 0, width = .2) +
  labs(x = &quot;&quot;, y = &quot;&quot;) +
  facet_wrap(~ metric, scales = &quot;free&quot;) +
  theme(legend.position=&quot;none&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/alpha-1.png" width="672" /></p>
<pre class="r"><code>#Summarize
adiv %&gt;%
  group_by(Status) %&gt;%
  dplyr::summarise(median_observed = median(Observed),
            median_shannon = median(Shannon),
            median_pd = median(PD))</code></pre>
<pre><code>## # A tibble: 2 x 4
##   Status          median_observed median_shannon median_pd
##   &lt;fct&gt;                     &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
## 1 Control                      49           2.40      18.1
## 2 Chronic Fatigue              46           2.30      17.0</code></pre>
<pre class="r"><code>#Wilcoxon test of location
wilcox.test(Observed ~ Status, data = adiv, exact = FALSE, conf.int = TRUE)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Observed by Status
## W = 1007.5, p-value = 0.2146
## alternative hypothesis: true location shift is not equal to 0
## 95 percent confidence interval:
##  -1.000059  5.000002
## sample estimates:
## difference in location 
##               2.000087</code></pre>
<pre class="r"><code>wilcox.test(Shannon ~ Status, data = adiv, conf.int = TRUE)              </code></pre>
<pre><code>## 
##  Wilcoxon rank sum test
## 
## data:  Shannon by Status
## W = 1037, p-value = 0.1329
## alternative hypothesis: true location shift is not equal to 0
## 95 percent confidence interval:
##  -0.04346366  0.39218192
## sample estimates:
## difference in location 
##              0.1421467</code></pre>
<pre class="r"><code>wilcox.test(PD ~ Status, data = adiv, conf.int = TRUE)</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test
## 
## data:  PD by Status
## W = 995, p-value = 0.2616
## alternative hypothesis: true location shift is not equal to 0
## 95 percent confidence interval:
##  -0.7452342  2.1356893
## sample estimates:
## difference in location 
##              0.6854015</code></pre>
<p>Here we see a modestly lower median alpha-diversity in samples from participants with chronic fatigue when compared to healthy controls. However, the variation in alpha-diversity between groups is highly overlapping and we fail to reject the null hypothesis of no difference in location between groups.</p>
<p><br></p>
<p>Below is the code to estimate richness using breakaway. You will see some warnings. I plan to update this section with some additional data so check back soon.</p>
<pre class="r"><code>#Obtain breakaway estimates
ba_adiv &lt;- breakaway::breakaway(ps)
ba_adiv[1]
#Plot estimates
plot(ba_adiv, ps, color = &quot;Status&quot;)     
#Examine models
summary(ba_adiv) %&gt;%
  add_column(&quot;SampleNames&quot; = ps %&gt;% otu_table %&gt;% sample_names)  
#Test for group differnce
bt &lt;- breakaway::betta(summary(ba_adiv)$estimate,
                       summary(ba_adiv)$error,
                       make_design_matrix(ps, &quot;Status&quot;))
bt$table                                                        </code></pre>
<p><br></p>
</div>
<div id="beta-diversity" class="section level1">
<h1>Beta-diversity</h1>
<p><strong>Beta-diversity provides a measure of similarity, or dissimilarity, of one microbial composition to another.</strong> Beta-diversity is typically calculated on the OTU/ASV/species composition tables directly (after normalization), but can be calculated using abundances at higher taxonomic levels. One common estimator of microbial beta-diversity is the pairwise <a href="https://en.wikipedia.org/wiki/Euclidean_distance">Euclidean distance</a> between samples. However, many ecologically informative measures are also commonly used and include:</p>
<ul>
<li>Bray-Curtis similarity</li>
<li>Jaccard similarity</li>
<li>Yue &amp; Clayton theta similarity</li>
<li><a href="https://aem.asm.org/content/71/12/8228">UniFrac distance</a></li>
<li><strong>AND MANY MORE</strong></li>
</ul>
<p>Pat Schloss provides a listing and links to a large number of alpha- and beta-diversity estimators on his <a href="https://mothur.org/wiki/Calculators">mothur wiki page</a>. He also offers <a href="https://www.mothur.org/wiki/Workshops">workshops</a> on using mothur for processing amplicon sequence data and on using R for microbial ecologists a few times a year that I highly recommend.</p>
<p>This is probably a good time to touch on <strong>count normalization.</strong> One of the challenges we face working with NGS-derived sequence data is that <em>the total number of reads for each sample is not directly tied to the starting quantity of DNA.</em> You can think of the total reads (to a reasonable approximation) as getting assigned by a random sampling process where some samples just get doled out more reads. Thus, the <strong>total count does not carry any information on the absolute abundance of taxa.</strong> As long as the count is sufficiently large, it is just a factor that we want to account for in our analysis and is not of particular interest other than differences across samples can be a source of bias. Paul McMurdie provides an excellent discussion of the various goals and some approaches for normalization in his chapter on <a href="https://experiments.springernature.com/articles/10.1007/978-1-4939-8728-3_10">Normalization of Microbiome Profiling Data</a> in the first edition of <a href="https://www.springer.com/us/book/9781493987269?gclid=Cj0KCQjw3uboBRDCARIsAO2XcYCprgmMyNEyKBS0QWmqNSUSfbZ8yiN29s1HjVYYGx3T7Z-Qmylv5x8aAoRLEALw_wcB">Microbiome Analysis</a>. <a href="https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-017-0237-y">Weiss et. al.</a> also provide a great introduction and examination of the impact of normalization approaches on beta-diversity ordinations and differential abundance testing.</p>
<p>Here we will consider two approaches for library size normalization. The first will employ a <strong>compositional data analysis approach</strong> and involves working with log-ratios. The second will involve simply subsampling the data without replacement; however, this approach comes with <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531">limiations</a>. We will use it here as the authors of the UniFrac method have suggested that rarefying more clearly clusters samples according to biological origin than other normalization techniques do for ordination metrics based on presence or absence (i.e. unweighted UniFrac).</p>
<p>A detailed discussion of compositional data analysis (CoDA) is beyond the scope of this session. I plan to add a tutorial devoted to CoDA in the future so check back. <strong>At a high-level</strong> compositional data (i.e. data that carry only relative information and are constrained by a unit sum) exist in a restricted subspace of the Euclidian geometry referred to as the D-1 simplex <em>(I know this doesn’t feel high-level)</em>. Due to this constraint, these data fail to meet many of the assumptions of our favorite statistical methods developed for unconstrained random variables. Working with ratios of compositional elements lets us transform these data to the Euclidian space and apply our favorite methods (so we don’t need to work in the simplex). Working with their logarithms makes them easier to interpret. There are different types of log-ratio “transformations” including the additive log-ratio, centered log-ratio, and isometric log-ratio transforms. Below are some great resources for learning more about compositional data analysis:</p>
<p>*<a href="https://academic.oup.com/bioinformatics/article/34/16/2870/4956011">Understanding sequencing data as compositions: an outlook and review</a> by Quinn et. al. in Bioinformatics (2018)</p>
<p>*<a href="https://www.springer.com/us/book/9789811315336?gclid=Cj0KCQjw3uboBRDCARIsAO2XcYAphJ23am-AoIBh18HoW-WpAd8TwbQUEhc_DJV9gM-zWYtXe0-6l8saAkNHEALw_wcB">Statistical Analysis of Microbiome Data with R - Ch. 10</a></p>
<p>*<a href="https://www.springer.com/gp/book/9783319964201">Applied Compositional Data Analysis</a> by Filzmoser, Hron, and Templ (2018)</p>
<p>*<a href="https://www.springer.com/gp/book/9783642368080">Analyzing Compositional Data with R</a> by Boogaart and Tolosana-Delgado (2013)</p>
<p><br></p>
<p>Below we generate a beta-diversity ordination using the Aitchison distance. This is simply applying PCA to the <a href="https://en.wikipedia.org/wiki/Compositional_data#Center_logratio_transform">centered log-ratio</a> (CLR) transformed counts. We will use the microbiome package to do this and assign a pseudocount of 1 to facilitate the transformation (since the log of zero is undefined). There are alternative/better approaches than using a pseudocount and we will examine one in the next section. First we perform the transformation.</p>
<pre class="r"><code>#CLR transform
(ps_clr &lt;- microbiome::transform(ps, &quot;clr&quot;))          </code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 138 taxa and 84 samples ]
## sample_data() Sample Data:       [ 84 samples by 23 sample variables ]
## tax_table()   Taxonomy Table:    [ 138 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 138 tips and 137 internal nodes ]
## refseq()      DNAStringSet:      [ 138 reference sequences ]</code></pre>
<pre class="r"><code>phyloseq::otu_table(ps)[1:5, 1:5]</code></pre>
<pre><code>## OTU Table:          [5 taxa and 5 samples]
##                      taxa are rows
##      ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851
## OTU1          2        581        347        916      10498
## OTU2        371         46          0        233        301
## OTU3       1189         81        637        199          0
## OTU4          0        172        246          0        372
## OTU5        308         44        143        155        221</code></pre>
<pre class="r"><code>phyloseq::otu_table(ps_clr)[1:5, 1:5]</code></pre>
<pre><code>## OTU Table:          [5 taxa and 5 samples]
##                      taxa are rows
##      ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851
## OTU1   1.289544   5.812706   5.615063   6.230204   9.467837
## OTU2   6.485240   3.280355  -3.079591   4.863001   5.916398
## OTU3   7.649802   3.844401   6.222432   4.705673  -1.903003
## OTU4  -2.317399   4.596219   5.271139  -1.178342   6.128105
## OTU5   6.299168   3.236089   4.728822   4.456584   5.607596</code></pre>
<p>We can see that the values are now no longer counts, but rather the dominance (or lack thereof) for each taxa relative to the geometric mean of all taxa on the logarithmic scale (any log base could be used and often log2 or log10 may aid in interpretation).</p>
<p><br></p>
<p>Now we will conduct the PCA, examine the relative importance of each principal component, and generate the ordination. <strong>PCA is an unsupervised learning approach</strong> that can help us see similarities between samples when there are a large number of features. Scatter plots are not much help here in high-dimensions since the number of possible plots is equal to p(p-1)<sup>2</sup> where p = the number of features (quickly becomes intractable). So we need to find an approach that will let us map these data to a lower-dimensional space. This is what PCA does. It identifies latent variables referred to as principal components (PC) that capture as much of the information as possible…where information is the amount of variation in the data. We can then focus on those PCs that are most interesting (i.e. explain the most variation; give us the best lower-dimensional mapping). Given we can only visualize our samples in 2- or 3-dimenstional space, most microbiome studies only plot the data using either the first couple of PCs. A more though introduction to PCA can be found in the textbook <a href="http://www-bcf.usc.edu/~gareth/ISL/">An Introduction to Statistical Learning</a> by James, Witten, Hastie, and Tibshirani (2013). Let’s give it a try!</p>
<pre class="r"><code>#PCA via phyloseq
ord_clr &lt;- phyloseq::ordinate(ps_clr, &quot;RDA&quot;)
#Plot scree plot
phyloseq::plot_scree(ord_clr) + 
  geom_bar(stat=&quot;identity&quot;, fill = &quot;blue&quot;) +
  labs(x = &quot;\nAxis&quot;, y = &quot;Proportion of Variance\n&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/pca%20scree-1.png" width="1152" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Examine eigenvalues and % prop. variance explained
head(ord_clr$CA$eig)                                                  </code></pre>
<pre><code>##      PC1      PC2      PC3      PC4      PC5      PC6 
## 75.69204 36.27003 33.16649 29.08833 25.52986 24.32215</code></pre>
<pre class="r"><code>sapply(ord_clr$CA$eig[1:5], function(x) x / sum(ord_clr$CA$eig))     </code></pre>
<pre><code>##        PC1        PC2        PC3        PC4        PC5 
## 0.10744095 0.05148344 0.04707812 0.04128939 0.03623832</code></pre>
<p>RDA without constraints is PCA…and we can generate the PCs using the phyloseq::ordinate function. A scree plot is then used to examine the proportion of total variation explained by each PC. Here we see that the first PC really stands out and then we have a gradual decline for the remaining components. You may hear people talk about looking for the “elbow” in the plot where the information plateaus to select the number of PCs to retain. Below we plot the first two components and scale the plot to reflect the relative amount of information explained by each axis as recommended by Nguyen and Holmes in their paper <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006907">Ten quick tips for effective dimensionality reduction</a>.</p>
<p><br></p>
<pre class="r"><code>#Scale axes and plot ordination
clr1 &lt;- ord_clr$CA$eig[1] / sum(ord_clr$CA$eig)
clr2 &lt;- ord_clr$CA$eig[2] / sum(ord_clr$CA$eig)
phyloseq::plot_ordination(ps, ord_clr, type=&quot;samples&quot;, color=&quot;Status&quot;) + 
  geom_point(size = 2) +
  coord_fixed(clr2 / clr1) +
  stat_ellipse(aes(group = Status), linetype = 2)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/plot%20pca-1.png" width="672" /></p>
<p>We see some separation between the chronic fatigue and healthy controls samples suggesting some differences in the communities according to sample type. There is also a fair degree of overlap as is often seen in clinical research studies examining the same environment in two different patient populations. While PCA is an exploratory data visualization tool, we can test whether the samples cluster beyond that expected by sampling variability using <a href="http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/adonis.html">permutational multivariate analysis of variance</a> (PERMANOVA). It does this by partitioning the sums of squares for the within- and between-cluster components using the concept of centroids. Many permutations of the data (i.e. random shuffling) are used to generate the null distribution. The test from ADONIS can be confounded by differences in dispersion (or spread)…so we want to check this as well.
<br></p>
<pre class="r"><code>#Generate distance matrix
clr_dist_matrix &lt;- phyloseq::distance(ps_clr, method = &quot;euclidean&quot;) 
#ADONIS test
vegan::adonis(clr_dist_matrix ~ phyloseq::sample_data(ps_clr)$Status)</code></pre>
<pre><code>## 
## Call:
## vegan::adonis(formula = clr_dist_matrix ~ phyloseq::sample_data(ps_clr)$Status) 
## 
## Permutation: free
## Number of permutations: 999
## 
## Terms added sequentially (first to last)
## 
##                                      Df SumsOfSqs MeanSqs F.Model      R2
## phyloseq::sample_data(ps_clr)$Status  1      2240 2240.17  3.2666 0.03831
## Residuals                            82     56233  685.77         0.96169
## Total                                83     58473                 1.00000
##                                      Pr(&gt;F)    
## phyloseq::sample_data(ps_clr)$Status  0.001 ***
## Residuals                                      
## Total                                          
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>#Dispersion test and plot
dispr &lt;- vegan::betadisper(clr_dist_matrix, phyloseq::sample_data(ps_clr)$Status)
dispr</code></pre>
<pre><code>## 
##  Homogeneity of multivariate dispersions
## 
## Call: vegan::betadisper(d = clr_dist_matrix, group =
## phyloseq::sample_data(ps_clr)$Status)
## 
## No. of Positive Eigenvalues: 83
## No. of Negative Eigenvalues: 0
## 
## Average distance to median:
##         Control Chronic Fatigue 
##            25.1            26.2 
## 
## Eigenvalues for PCoA axes:
## (Showing 8 of 83 eigenvalues)
## PCoA1 PCoA2 PCoA3 PCoA4 PCoA5 PCoA6 PCoA7 PCoA8 
##  6282  3010  2753  2414  2119  2019  1895  1693</code></pre>
<pre class="r"><code>plot(dispr, main = &quot;Ordination Centroids and Dispersion Labeled: Aitchison Distance&quot;, sub = &quot;&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/adonis-1.png" width="672" /></p>
<pre class="r"><code>boxplot(dispr, main = &quot;&quot;, xlab = &quot;&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/adonis-2.png" width="672" /></p>
<pre class="r"><code>permutest(dispr)</code></pre>
<pre><code>## 
## Permutation test for homogeneity of multivariate dispersions
## Permutation: free
## Number of permutations: 999
## 
## Response: Distances
##           Df Sum Sq Mean Sq      F N.Perm Pr(&gt;F)  
## Groups     1  24.95 24.9463 3.0491    999  0.075 .
## Residuals 82 670.89  8.1816                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We reject the null hypothesis of no difference in the centroid location according to Status. However, the proportion of variance explained is quite small. You might get slightly different numbers. This is because of the random process generating the permutations. There is a suggestion that the dispersion is greater in samples from patients with chronic fatigue syndrome. However, it does not exceed that expected by sampling variablilty at this sample size.
As has been explained by others (Xia, Sun, and Chen; Ch 7.4), I want to mention that this type of testing is akin to <strong>attempting to “explain” the axes</strong> using metadata fields. A more formal approach to hypotheses testing can be done using <em>redundancy analysis or canonical correspondence analysis</em> that directly uses information on metadata fields when generating the ordinations and conducting testing. These approaches <em>directly</em> test hypotheses about environmental variables. I will not demonstrate these approaches here, but they can be computed using some of these same commands with minor modifications.</p>
<p>Lastly, I want to show you how you can bring in information the form of a phylogenic tree into beta-diversity analysis. The <strong>UniFrac metric</strong> incorporates phylogenic information by calculating the total branch lengths “unshared” between two samples divided by the total branch length. This approach often reveals interesting differences in the phylogenic relatedness between samples and sample types. Here we compute the weighted and unweighted UniFrac metrics using PCoA. PCoA can be thought of as PCA for non-Euclidian measures.</p>
<pre class="r"><code>#Generate distances
ord_unifrac &lt;- ordinate(ps_rare, method = &quot;PCoA&quot;, distance = &quot;wunifrac&quot;) 
ord_unifrac_un &lt;- ordinate(ps_rare, method = &quot;PCoA&quot;, distance = &quot;unifrac&quot;)   
#Plot ordinations
a &lt;- plot_ordination(ps_rare, ord_unifrac, color = &quot;Status&quot;) + geom_point(size = 2)
b &lt;- plot_ordination(ps_rare, ord_unifrac_un, color = &quot;Status&quot;) + geom_point(size = 2)
cowplot::plot_grid(a, b, nrow = 1, ncol = 2, scale = .9, labels = c(&quot;Weighted&quot;, &quot;Unweighted&quot;))</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/plot%20unifrac-1.png" width="1536" style="display: block; margin: auto;" /></p>
<p>There is a large amount of overlap between sample types for the weighted UniFrac distance (accounts for the relative abundance of each of the taxa within the communities). However, there is clustering on at least the first axis for the unweighted UniFrac distance that is not “explained” by Status. <em>Is there a metadata field in the data that reflects this separation?</em> I’ll let you explore on your own.</p>
<p><br></p>
</div>
<div id="differential-abundance-testing" class="section level1">
<h1>Differential abundance testing</h1>
<p>The goal of differential abundance testing is to <strong>identify specific taxa associated with clinical metadata variables of interest.</strong> This is a difficult task. It is also one of the more controversial areas in microbiome data analysis. Some of the reasons for this are described in a recent paper by James Morton et. al. in <a href="https://www.nature.com/articles/s41467-019-10656-5">Nature Communications</a> (2019), but is related to concerns that normalization and testing approaches have generally failed to control false discovery rates <a href="https://academic.oup.com/bib/article-abstract/20/1/210/4091293?redirectedFrom=fulltext">(here is a good example)</a> and this has contributed to the lack of reproducibility in microbiome studies. If you think about it for a moment, a couple of difficulties come to mind:</p>
<ul>
<li>The goal of this type of analysis is to identify taxa that differ the most between conditions (or along a continuous gradient). Basically, we are identifying the most extreme results in the data. We would therefore <strong>expect some/many/most of these findings to have been “outlying” results simply due to chance sampling variation</strong> and to perhaps <a href="https://en.wikipedia.org/wiki/Regression_toward_the_mean">regress back towards the mean/null value</a> when tested in a new sample of patients.</li>
<li>The data are compositional and thus changes in one or more taxa can make it look like other/all taxa are changing. James Morton has an excellent example of this <a href="https://docs.qiime2.org/2019.4/tutorials/gneiss/">here</a>. Methods that don’t properly account of the compositional nature of the data can have <a href="https://microbiomejournal.biomedcentral.com/articles/10.1186/s40168-016-0208-8">very high false discovery rates.</a>.</li>
<li>Functionally redundant taxa may serve the same “niche” in different environments or populations causing different taxa to be identified as differentially abundant across samples (however the testing approach would not be what is misleading here).</li>
<li>The high correlation between many taxa may cause different, but highly correlated, features to be selected in different studies.</li>
</ul>
<p>Professor Frank Harrell provides a great overview of this general concern in Chapter 20 of his <a href="http://hbiostat.org/doc/bbr.pdf">Biostatistics for Biomedical Research</a> online text. For general thoughts on statistics and predictive modeling I highly recommend that you check out his <a href="https://www.fharrell.com/#links">blog</a> and <a href="http://biostat.mc.vanderbilt.edu/wiki/Main/RmS">regression modeling strategies</a> course notes.</p>
<p>Other fields have wrestled with similar problems and have introduced approaches such as the requirement of replicating results in multiple cohorts of patients prior to publication (or at least employing rigorous resampling approaches to gauge the reproducibility), analysis pre-specification, and focusing more on prediction than “naming names”. For compositional data including external information in the form of external spike-ins or estimates of total abundance (such as estimating total microbial load using qPCR), working with ratios, limiting the emphasis on testing, and understanding the limits of compositional data are likely reasonable ways forward here. However, <strong>none of these are a panacea.</strong> Methodologists working in the area of microbiome data analysis are addressing some of these issues, but there is still much work to be done. Two excellent recent papers you should check out include James Morton’s paper above and this <a href="https://www.biorxiv.org/content/10.1101/559831v1">preprint</a> in biorxiv by McLaren, Willis and Callahan (2019) explaining and modeling correctable bias in metagenomic sequence studies.</p>
<p>In this section, I will present a two approaches for estimating differential abundance. The first is simply applying the non-parametric Wilcoxon rank-sum test to each taxon. The second is a version of the Wilcoxon test developed for compositional NGS data. I chose these two approaches since they are commonly used in microbiome studies and I expect many of you will have some familiarity with the Wilcoxon test or (Gosset’s) t-test. However, all results should be interpreted in light of the concerns raised above. I also include the use of a CoDA transform for both since there does seem to be some growing support that log-ratio methodologies may better control the false positive rate.</p>
<p>Many researchers will apply the non-parametric Wilcoxon rank-sum test to each OTU/ASV/species after normalization. We will do this here. We will also use <strong>nested data frames</strong> as advocated by Hadley Wickham to keep the data and test results together in a single data.frame. <em>At first, I found this approach a little strange.</em> However, I have come to use it all the time. It is perhaps a bit overkill here, but a very helpful framework when you want to run many models and then save them together with the data and results (especially when they take a long time to run). Here is a <a href="https://r4ds.had.co.nz/many-models.html">link to a complete description of the nested frame approach</a> in the R for Data Science book. We also use the map function from purr. This operates like a for loop, allowing us to iterate the test over each OTU, but with less coding. This is a big chunk of code. I will talk you through it.</p>
<pre class="r"><code>#Generate data.frame with OTUs and metadata
ps_wilcox &lt;- data.frame(t(data.frame(phyloseq::otu_table(ps_clr))))
ps_wilcox$Status &lt;- phyloseq::sample_data(ps_clr)$Status
#Define functions to pass to map
wilcox_model &lt;- function(df){
  wilcox.test(abund ~ Status, data = df)
}
wilcox_pval &lt;- function(df){
  wilcox.test(abund ~ Status, data = df)$p.value
}
#Create nested data frames by OTU and loop over each using map 
wilcox_results &lt;- ps_wilcox %&gt;%
  gather(key = OTU, value = abund, -Status) %&gt;%
  group_by(OTU) %&gt;%
  nest() %&gt;%
  mutate(wilcox_test = map(data, wilcox_model),
         p_value = map(data, wilcox_pval))                       
#Show results
head(wilcox_results)</code></pre>
<pre><code>## # A tibble: 6 x 4
##   OTU   data              wilcox_test p_value  
##   &lt;chr&gt; &lt;list&gt;            &lt;list&gt;      &lt;list&gt;   
## 1 OTU1  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;
## 2 OTU2  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;
## 3 OTU3  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;
## 4 OTU4  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;
## 5 OTU5  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;
## 6 OTU6  &lt;tibble [84 x 2]&gt; &lt;S3: htest&gt; &lt;dbl [1]&gt;</code></pre>
<pre class="r"><code>head(wilcox_results$data[[1]])</code></pre>
<pre><code>## # A tibble: 6 x 2
##   Status          abund
##   &lt;fct&gt;           &lt;dbl&gt;
## 1 Chronic Fatigue  1.29
## 2 Control          5.81
## 3 Control          5.62
## 4 Chronic Fatigue  6.23
## 5 Chronic Fatigue  9.47
## 6 Control          7.43</code></pre>
<pre class="r"><code>wilcox_results$wilcox_test[[1]]</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test
## 
## data:  abund by Status
## W = 1172, p-value = 0.006066
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<pre class="r"><code>wilcox_results$p_value[[1]]</code></pre>
<pre><code>## [1] 0.006066387</code></pre>
<p>Here we can see that we have a tibble where:</p>
<ul>
<li>each OTU is a row</li>
<li>the data column contains a tibble for each OTU that contains the CLR abundance and Status fields (i.e. seperate data.frame for each OTU)</li>
<li>the wilcox_test column contains the results of each Wilcoxon test</li>
<li>the p_value column contains the extracted p-value for each test</li>
</ul>
<p><br></p>
<p>Now we will unnest the results, grab the OTU names and p-values, add the taxonomic labels, and calculate the FDR adjusted p-values.</p>
<pre class="r"><code>#Unnesting
wilcox_results &lt;- wilcox_results %&gt;%
  dplyr::select(OTU, p_value) %&gt;%
  unnest()
head(wilcox_results)</code></pre>
<pre><code>## # A tibble: 6 x 2
##   OTU   p_value
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 OTU1  0.00607
## 2 OTU2  0.0686 
## 3 OTU3  0.830  
## 4 OTU4  0.0130 
## 5 OTU5  0.419  
## 6 OTU6  0.258</code></pre>
<pre class="r"><code>#Adding taxonomic labels
taxa_info &lt;- data.frame(tax_table(ps_clr))
taxa_info &lt;- taxa_info %&gt;% rownames_to_column(var = &quot;OTU&quot;)
#Computing FDR corrected p-values
wilcox_results &lt;- wilcox_results %&gt;%
  full_join(taxa_info) %&gt;%
  arrange(p_value) %&gt;%
  mutate(BH_FDR = p.adjust(p_value, &quot;BH&quot;)) %&gt;%
  filter(BH_FDR &lt; 0.05) %&gt;%
  dplyr::select(OTU, p_value, BH_FDR, everything())</code></pre>
<pre><code>## Joining, by = &quot;OTU&quot;</code></pre>
<pre class="r"><code>#Printing results
print.data.frame(wilcox_results)  </code></pre>
<pre><code>##      OTU      p_value      BH_FDR  Kingdom     Phylum           Class
## 1  OTU48 1.893126e-05 0.002612514 Bacteria Firmicutes      Clostridia
## 2  OTU38 4.168412e-05 0.002876205 Bacteria Firmicutes      Clostridia
## 3  OTU44 2.750125e-04 0.012650574 Bacteria Firmicutes      Clostridia
## 4  OTU61 1.217944e-03 0.038379997 Bacteria Firmicutes      Clostridia
## 5 OTU104 1.390580e-03 0.038379997 Bacteria Firmicutes      Clostridia
## 6 OTU115 1.804359e-03 0.040427044 Bacteria Firmicutes      Clostridia
## 7  OTU83 2.050647e-03 0.040427044 Bacteria Firmicutes      Clostridia
## 8   OTU8 2.719699e-03 0.041702048 Bacteria Firmicutes      Clostridia
## 9 OTU123 2.719699e-03 0.041702048 Bacteria Firmicutes Erysipelotrichi
##                Order              Family          Genus  Species
## 1      Clostridiales     Lachnospiraceae    Coprococcus     &lt;NA&gt;
## 2      Clostridiales     Ruminococcaceae   Oscillospira     &lt;NA&gt;
## 3      Clostridiales     Lachnospiraceae [Ruminococcus]     &lt;NA&gt;
## 4      Clostridiales     Lachnospiraceae           &lt;NA&gt;     &lt;NA&gt;
## 5      Clostridiales     Lachnospiraceae        Blautia producta
## 6      Clostridiales  [Mogibacteriaceae]           &lt;NA&gt;     &lt;NA&gt;
## 7      Clostridiales     Lachnospiraceae        Blautia     &lt;NA&gt;
## 8      Clostridiales     Lachnospiraceae [Ruminococcus]     &lt;NA&gt;
## 9 Erysipelotrichales Erysipelotrichaceae  Coprobacillus     &lt;NA&gt;</code></pre>
<p>Here we see that we have several Clostridiales organisms identified as differentially abundant. Next, we might use bootstrap resampling to see how often these results replicated in subsets of the data and calculate a measure of effect size. However, we will not do that here. Instead we will take a look at another approach that uses the Wilcoxon test on the CLR transformed data with some improvements in the treatment of zero values and presentation of effect size.</p>
<p><br></p>
<p><strong>ANOVA-like differential expression (ALDEx2)</strong> is a popular CoDA method for differential abundance testing. ALDEx2 can be run via a single command; however, there are several steps that are occurring in the background. <strong>At a high-level</strong>, the steps include:</p>
<ul>
<li>Generate a large number (here n=128) of posterior probabilities for the observance of each taxon (i.e. output many data.frames where the counts have been converted to proportions). This is done by Monte-Carlo sampling from a Dirichlet distribution with a small non-zero prior to deal with zeros. The total read count therefore only contributes to the precision of the proportions.</li>
<li>Apply the centered log-ratio transformation to each instance.</li>
<li>Apply the Wilcoxon test to each taxon for each simulated instance.</li>
<li>Estimate the effect size as the difference between conditions divided by the maximum difference within conditions averaging over all instances. Scaling the between group difference by the maximum within group difference gives us a standardized effect size measure.</li>
<li>Obtain the expected p-values for each taxon by averaging over all instances.</li>
<li>Apply the BH-FDR correction to control the false positive rate.</li>
</ul>
<p>For a more through explanation see the <a href="https://www.bioconductor.org/packages/release/bioc/vignettes/ALDEx2/inst/doc/ALDEx2_vignette.pdf">ALDEx2 Bioconductor vignette</a>.</p>
<p>Lets give it a try.</p>
<pre class="r"><code>#Run ALDEx2
aldex2_da &lt;- ALDEx2::aldex(data.frame(phyloseq::otu_table(ps)), phyloseq::sample_data(ps)$Status, test=&quot;t&quot;, effect = TRUE, denom=&quot;iqlr&quot;)</code></pre>
<pre><code>## aldex.clr: generating Monte-Carlo instances and clr values</code></pre>
<pre><code>## operating in serial mode</code></pre>
<pre><code>## computing iqlr centering</code></pre>
<pre><code>## aldex.ttest: doing t-test</code></pre>
<pre><code>## aldex.effect: calculating effect sizes</code></pre>
<pre class="r"><code>#Plot effect sizes
ALDEx2::aldex.plot(aldex2_da, type=&quot;MW&quot;, test=&quot;wilcox&quot;, called.cex = 1, cutoff = 0.05)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/aldex2-1.png" width="672" /></p>
<p>The output highlights the various steps for the ALDEx2 workflow. The interquartile log-ratio (iqlr) centering uses as the basis for the CLR transform the set of features that have variance values that fall between the first and third quartiles for all features in all groups in the dataset. This provides results that are more robust to asymmetric features between groups.</p>
<p>The effect size plot shows the median log2 fold difference by the median log2 dispersion. This is a measure of the effect size by the variability. Differentially abundant taxon will be those where the difference most exceeds the dispersion. Points toward the top of the figure are more abundant in CF samples while those towards the bottom are more abundant in healthy controls. Taxa with BH-FDR corrected p-values are shown in red. However, the authors state that:</p>
<blockquote>
<p>We prefer to use the effect size whenever possible rather than statistical significance since an effect size tells the scientist what they want to know—“what is reproducibly different between groups”; this is emphatically not something that P values deliver.
Now we will print the output with the taxonomic classifications appended. WE use the FDR p-values here to facilitate the comparison with the results from Wilcoxon test ran outside of ALDEx2.</p>
</blockquote>
<pre class="r"><code>#Clean up presentation
sig_aldex2 &lt;- aldex2_da %&gt;%
  rownames_to_column(var = &quot;OTU&quot;) %&gt;%
  filter(wi.eBH &lt; 0.05) %&gt;%
  arrange(effect, wi.eBH) %&gt;%
  dplyr::select(OTU, diff.btw, diff.win, effect, wi.ep, wi.eBH)
sig_aldex2 &lt;- left_join(sig_aldex2, taxa_info)</code></pre>
<pre><code>## Joining, by = &quot;OTU&quot;</code></pre>
<pre class="r"><code>sig_aldex2</code></pre>
<pre><code>##     OTU  diff.btw diff.win     effect        wi.ep      wi.eBH  Kingdom
## 1  OTU8 -2.307035 5.522587 -0.3839105 0.0015096450 0.039837292 Bacteria
## 2 OTU48  3.639216 6.528139  0.5283635 0.0025403967 0.042007768 Bacteria
## 3 OTU44  3.541267 6.324375  0.5296702 0.0013725146 0.031600961 Bacteria
## 4 OTU38  3.277257 4.696329  0.6206553 0.0000348666 0.004124241 Bacteria
##       Phylum      Class         Order          Family          Genus
## 1 Firmicutes Clostridia Clostridiales Lachnospiraceae [Ruminococcus]
## 2 Firmicutes Clostridia Clostridiales Lachnospiraceae    Coprococcus
## 3 Firmicutes Clostridia Clostridiales Lachnospiraceae [Ruminococcus]
## 4 Firmicutes Clostridia Clostridiales Ruminococcaceae   Oscillospira
##   Species
## 1    &lt;NA&gt;
## 2    &lt;NA&gt;
## 3    &lt;NA&gt;
## 4    &lt;NA&gt;</code></pre>
<p>Here we see that again that several Clostridiales organisms are identified as differentially abundant. Consistent with the results of running the Wilcoxon test outside of ALDEx2, we see that OTU48, OTU38, OTU44, and OTU8 are listed as differentially abundant. The others do not reach the FDR cut-off used here; although, they likely have “largish” effect sizes. <em>Try and see if you can obtain these values.</em> The reason for the discrepancy is hard to discern, but may be related to differences in the use of the CLR basis (geometric mean of all taxa versus the IQLR) and/or the use of the Bayesian resampling with a non-zero prior.</p>
<p>Often, if I consider performing DA testing, <strong>I will run several models and focus on the intersection of OTUs</strong> and try to gain some insight into how the different normalization and/or models many be influencing the results.</p>
<p>There are <strong>MANY</strong> other approaches that can be used to attempt to identify differently abundant taxa. Some that are popular, or that I find interesting, and can be implemented in R include:</p>
<ul>
<li>Count Regression for Correlated Observations with the Beta-binomial <a href="https://github.com/bryandmartin/corncob">(corncob)</a></li>
<li><a href="https://academic.oup.com/bioinformatics/article/34/4/643/4470360">MicrobiomeDDA</a></li>
<li><a href="https://joey711.github.io/phyloseq-extensions/DESeq2.html">DESeq2</a></li>
<li><a href="https://sites.google.com/site/siddharthamandal1985/research">Analysis of Composition of Microbiomes (ANCOM)</a></li>
</ul>
<p>Outside of R, a recently developed approach using <a href="https://github.com/biocore/songbird">multinomial regression via tensorflow</a> and differential ranking looks promising.</p>
<p><br></p>
</div>
<div id="prediction" class="section level1">
<h1>Prediction</h1>
<p>As discussed by Dr. Haslam in the first lecture, the majority of clinical microbiome studies, conducted to date, have been correlative or focused on predicting outcomes using taxonomic abundances as the feature set. <strong>The predictive utility of the human microbiome in health and disease is of great interest</strong> and numerous studies have reported the ability to predict outcomes from metagenomic data. For example, here are links to three studies suggesting taxonomic profiles in fecal samples may predict the occurrence of colorectal cancer (<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5989068/">1</a>, <a href="https://www.nature.com/articles/s41591-019-0405-7">2</a>, <a href="https://www.nature.com/articles/s41591-019-0406-6">3</a>).</p>
<p>As with differential abundance testing, there are many models or statistical learning approaches that can be applied to metagenomic data for the purpose of predicting an outcome. For binary outcomes, generating predicted probabilities for the outcome of interest using generalized linear models (GLMs) is one approach. Machine learning approaches have also been used extensively in microbiome research; however, these approaches may likely require much larger datasets than they have typically been trained on if our goal is reproducible results (the same likely goes for most studies using GLMs, etc.).</p>
<p>One challenge we face when building a predictive model from metagenomic data is that <strong>we often have more features (taxon) than we have samples.</strong> For example, if we are working with microbial strains we might have more than 10,000 features to consider. One way to define high-dimensional data is when <em>p</em> &gt; <em>n</em>, where: p = number of features and n = the number of samples. In these instances, one approach forward to reduce the dimensionality of the data. We did this earlier when we used PCA to extract the first two PCs that explained the largest fraction of variably in our data. Using a subset of the PCs as predictors in a GLM is known as principal components regression. We will give this approach a try below. Another is to include all the features as predictors, but to shrink their effects towards zero (or sometimes shrink them entirely out of the model). These approaches go by names such as ridge regression, LASSO, elastic nets, etc. Bayesian models with skeptical priors also can work well here. We will use a form of penalization on the principal components regression model below to highlight this approach and address potential overfitting even with just three PCs at this sample size (which is likely too small for robust prediction). A helpful guide to think about how many features or samples one might require to develop a predictive model is to consider how much overfitting you are willing to accept. Here are links to two excellent papers describing sample size determinations for <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/sim.7993">continuous</a> and <a href="https://onlinelibrary.wiley.com/doi/full/10.1002/sim.7992">binary</a> outcomes in predictive modeling.</p>
<p>We will also examine a CoDA greedy stepwise selection model using balances that I think is a lot of fun…and very user-friendly.</p>
<p>For those interested in general resources for prediction modeling I recommend:</p>
<ul>
<li>Frank Harrell’s Regression Modeling Stratagies <a href="http://biostat.mc.vanderbilt.edu/wiki/Main/RmS">website</a> and <a href="https://www.springer.com/us/book/9783319194240#aboutBook">textbook</a></li>
<li>Ewout Steyerberg’s Clinical Prediction Models <a href="https://www.springer.com/gp/book/9780387772431">textbook</a> for a bit more introductory text</li>
<li>Max Kuhn’s Applied Predictive Modeling <a href="http://appliedpredictivemodeling.com/">textbook</a></li>
<li>James, Witten, Hastie, and Tibshirani’s <a href="http://www-bcf.usc.edu/~gareth/ISL/">An Introduction to Statistical Learning</a></li>
</ul>
<p>First we will create a data.frame that contains the Status and the first 3 PCs from the centered-log ratio transformed abundance table we generated before. We will then plot the unconditional association for each PC with the outcome of CF versus control.</p>
<pre class="r"><code>#Generate data.frame
clr_pcs &lt;- data.frame(
  &quot;pc1&quot; = ord_clr$CA$u[,1],
  &quot;pc2&quot; = ord_clr$CA$u[,2],
  &quot;pc3&quot; = ord_clr$CA$u[,3],
  &quot;Status&quot; = phyloseq::sample_data(ps_clr)$Status
)
clr_pcs$Status_num &lt;- ifelse(clr_pcs$Status == &quot;Control&quot;, 0, 1)
head(clr_pcs)</code></pre>
<pre><code>##                    pc1         pc2           pc3          Status
## ERR1331793  0.02850343 -0.07709724  0.0938970408 Chronic Fatigue
## ERR1331872 -0.08156129  0.14193568  0.1155088427         Control
## ERR1331819 -0.19356039 -0.08436341 -0.1048722096         Control
## ERR1331794 -0.04193714  0.09705602  0.0110912849 Chronic Fatigue
## ERR1331851  0.09994410  0.05534786 -0.0005008101 Chronic Fatigue
## ERR1331834 -0.15577774  0.02921040 -0.0204667015         Control
##            Status_num
## ERR1331793          1
## ERR1331872          0
## ERR1331819          0
## ERR1331794          1
## ERR1331851          1
## ERR1331834          0</code></pre>
<pre class="r"><code>#Specify a datadist object (for rms)
dd &lt;- datadist(clr_pcs)
options(datadist = &quot;dd&quot;)
#Plot the unconditional associations
a &lt;- ggplot(clr_pcs, aes(x = pc1, y = Status_num)) +
  Hmisc::histSpikeg(Status_num ~ pc1, lowess = TRUE, data = clr_pcs) +
  labs(x = &quot;\nPC1&quot;, y = &quot;Pr(Chronic Fatigue)\n&quot;)
b &lt;- ggplot(clr_pcs, aes(x = pc2, y = Status_num)) +
  Hmisc::histSpikeg(Status_num ~ pc2, lowess = TRUE, data = clr_pcs) +
  labs(x = &quot;\nPC2&quot;, y = &quot;Pr(Chronic Fatigue)\n&quot;)
c &lt;- ggplot(clr_pcs, aes(x = pc3, y = Status_num)) +
  Hmisc::histSpikeg(Status_num ~ pc3, lowess = TRUE, data = clr_pcs) +
  labs(x = &quot;\nPC3&quot;, y = &quot;Pr(Chronic Fatigue)\n&quot;)
cowplot::plot_grid(a, b, c, nrow = 2, ncol = 2, scale = .9, labels = &quot;AUTO&quot;)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/plot%20pcs-1.png" width="672" /></p>
<p>We see that we have the potential for some non-linear associations. Professor Harrell recommends that it is generally a good idea to assume some level of complexity since the penalty for allowing for a non-linear fit, when the association is in fact linear, is much less than when assuming linearity when the association is non-linear (i.e. you fit a straight line through a u-shaped curve). His <a href="https://cran.r-project.org/web/packages/rms/index.html">rms package</a>, along with the tidyverse, are the two packages I use most often and allows us to model this type of complexity easily using <a href="https://towardsdatascience.com/restricted-cubic-splines-c0617b07b9a5">restricted cubic splines</a>. These are a set of highly flexible, smoothly joined, piecewise polynomials entered for each variable. The number and placement of the knots helps control the flexibility. We will allow three knots for each term. However, this results in an additional 3 (6 total) model degrees of freedom…but we will shrink this down.</p>
<p>We first fit the full model and then perform a grid search to identify the optimum value for the penalty. We can also allow the penalty to differ for the simple and complex (i.e. nonlinear or interactions) terms. This is helpful if we want to allow for complexity, but down weight its impact. This would kind of be like adding more restrictive priors to the non-linear terms in a Bayesian model. We then plot the penalized log odds.</p>
<pre class="r"><code>#Fit full model with splines (3 knots each)
m1 &lt;- rms::lrm(Status_num ~ rcs(pc1, 3) + rcs(pc2, 3) + rcs(pc3, 3), data = clr_pcs, x = TRUE, y = TRUE)
#Grid search for penalties
pentrace(m1, list(simple = c(0, 1, 2), nonlinear = c(0, 100, 200)))</code></pre>
<pre><code>## 
## Best penalty:
## 
##  simple nonlinear       df
##       1       200 2.783027
## 
##  simple nonlinear       df      aic       bic    aic.c
##       0         0 6.000000 23.10845  8.523552 22.01754
##       0       100 3.049209 28.21043 20.798359 27.90157
##       1       100 2.810152 28.38363 21.552668 28.11659
##       2       100 2.641219 28.11811 21.697792 27.87875
##       0       200 3.024831 28.24577 20.892958 27.94131
##       1       200 2.783027 28.42060 21.655570 28.15810
##       2       200 2.611196 28.15166 21.804324 27.91706</code></pre>
<pre class="r"><code>pen_m1 &lt;- update(m1, penalty = list(simple = 1, nonlinear = 200))
pen_m1</code></pre>
<pre><code>## Logistic Regression Model
##  
##  rms::lrm(formula = Status_num ~ rcs(pc1, 3) + rcs(pc2, 3) + rcs(pc3, 
##      3), data = clr_pcs, x = TRUE, y = TRUE, penalty = list(simple = 1, 
##      nonlinear = 200))
##  
##  
##  Penalty factors
##  
##   simple nonlinear interaction nonlinear.interaction
##        1       200         200                   200
##  
##                       Model Likelihood     Discrimination    Rank Discrim.    
##                          Ratio Test           Indexes           Indexes       
##  Obs            84    LR chi2    33.99     R2       0.421    C       0.848    
##   0             37    d.f.       2.783     g        1.759    Dxy     0.695    
##   1             47    Pr(&gt; chi2)&lt;0.0001    gr       5.807    gamma   0.695    
##  max |deriv| 1e-12    Penalty     2.34     gp       0.322    tau-a   0.347    
##                                            Brier    0.159                     
##  
##            Coef    S.E.   Wald Z Pr(&gt;|Z|) Penalty Scale
##  Intercept  0.3458 0.2852  1.21  0.2254   0.0000       
##  pc1       11.6489 2.8714  4.06  &lt;0.0001  0.1098       
##  pc1&#39;       0.1202 0.9287  0.13  0.8970   1.0715       
##  pc2        6.4946 2.5132  2.58  0.0098   0.1098       
##  pc2&#39;      -0.0015 0.7643  0.00  0.9984   1.2987       
##  pc3       -3.8538 2.5659 -1.50  0.1331   0.1098       
##  pc3&#39;       0.0259 1.0080  0.03  0.9795   0.9856       
## </code></pre>
<pre class="r"><code>#Plot log odds
ggplot(Predict(pen_m1))</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/rms%20lrm-1.png" width="672" /></p>
<p>We can see from the value of the penalties and the resultant log odds that the conditional associations are quite linear. However, we will leave in the cubic spline terms to fully account for the degrees of freedom we entertained in the model building process. The optimal penalties were 1 for the simple and 200 for the non-linear terms (higher is better for the corrected AIC) and the effective degrees of freedom shrunk to 2.78. We won’t interpret the coefficients here since we purposefully biased them towards zero.</p>
<p>The <a href="https://en.wikipedia.org/wiki/Brier_score">Brier score</a> is 0.16 and provides a measure of the mean squared difference between the predicted probabilities and actual outcomes. Thus, it is a quadratic proper scoring rule. The c-statistic is analogous to the area under the receiver operating characteristic curve and is a measure of rank discrimination. Here it is c = 0.85.</p>
<p><br></p>
<p>No we will perform bootstrap resampling to obtain an out-of-sample estimate of model performance. Here is a <a href="https://thestatsgeek.com/2014/10/04/adjusting-for-optimismoverfitting-in-measures-of-predictive-ability-using-bootstrapping/">link describing this in greater detail</a>.</p>
<pre class="r"><code>#Obtain optimism corrected estimates
(val &lt;- rms::validate(pen_m1))</code></pre>
<pre><code>##           index.orig training    test optimism index.corrected  n
## Dxy           0.6952   0.7248  0.6817   0.0431          0.6521 40
## R2            0.4206   0.4536  0.4295   0.0240          0.3965 40
## Intercept     0.0000   0.0000 -0.0250   0.0250         -0.0250 40
## Slope         1.0000   1.0000  1.0265  -0.0265          1.0265 40
## Emax          0.0000   0.0000  0.0100   0.0100          0.0100 40
## D             0.3927   0.4045  0.3749   0.0297          0.3630 40
## U            -0.0238  -0.0238 -0.0073  -0.0165         -0.0073 40
## Q             0.4165   0.4283  0.3822   0.0461          0.3704 40
## B             0.1589   0.1481  0.1647  -0.0166          0.1755 40
## g             1.7591   1.9083  1.9158  -0.0075          1.7666 40
## gp            0.3218   0.3287  0.3363  -0.0076          0.3293 40</code></pre>
<pre class="r"><code>#Compute corrected c-statistic
(c_opt_corr &lt;- 0.5 * (val[1, 5] + 1))</code></pre>
<pre><code>## [1] 0.8260443</code></pre>
<pre class="r"><code>#Plot calibration
cal &lt;- rms::calibrate(pen_m1, B = 200)
plot(cal)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/rms%20val-1.png" width="672" /></p>
<pre><code>## 
## n=84   Mean absolute error=0.01   Mean squared error=0.00018
## 0.9 Quantile of absolute error=0.024</code></pre>
<pre class="r"><code>#Output pred. probs
head(predict(pen_m1, type =&quot;fitted&quot;))</code></pre>
<pre><code>## ERR1331793 ERR1331872 ERR1331819 ERR1331794 ERR1331851 ERR1331834 
##  0.4560689  0.4689260  0.1137757  0.6098891  0.8683044  0.2314747</code></pre>
<p>We can see here that the Brier score is only mildly increased, and the c-statistic mildly decreased with repeated resampling. The calibration curve shows that the predictions are near the ideal across the range of predicted values. All-in-all this suggests we may expect to be able to predict patients with chronic fatigue from healthy controls with reasonable accuracy in a new sample of patients drawn from a similar population using just the three top PCs.</p>
<p><br></p>
<p><strong>Now we will quickly show selbal as an alternaitve.</strong> From the documentation selbal is described as:</p>
<blockquote>
<p>selbal is an R package for selection of balances in microbiome compositional data. As described in Rivera-Pinto et al. 2018 Balances: a new perspective for microbiome analysis <a href="https://doi.org/10.1101/219386" class="uri">https://doi.org/10.1101/219386</a>, selbal implements a forward-selection method for the identification of two groups of taxa whose relative abundance, or balance, is associated with the response variable of interest.
It requires much less typing…so let’s give it a go. This approach is computationally expensive (especially with larger datasets). So below we only use 1 repeat of 5-fold cross-validation to tune the selections. In practice, we would want to turn these numbers up to get better estimates. We will also aggregate the taxa to the family-level to speed up the computation.</p>
</blockquote>
<pre class="r"><code>#Agglomerate taxa
(ps_family &lt;- phyloseq::tax_glom(ps, &quot;Family&quot;))</code></pre>
<pre><code>## phyloseq-class experiment-level object
## otu_table()   OTU Table:         [ 30 taxa and 84 samples ]
## sample_data() Sample Data:       [ 84 samples by 23 sample variables ]
## tax_table()   Taxonomy Table:    [ 30 taxa by 7 taxonomic ranks ]
## phy_tree()    Phylogenetic Tree: [ 30 tips and 29 internal nodes ]
## refseq()      DNAStringSet:      [ 30 reference sequences ]</code></pre>
<pre class="r"><code>phyloseq::taxa_names(ps_family) &lt;- phyloseq::tax_table(ps_family)[, &quot;Family&quot;]
#Run selbal
cv_sebal &lt;- selbal::selbal.cv(x = data.frame(t(data.frame(phyloseq::otu_table(ps_family)))), 
                              y = phyloseq::sample_data(ps_family)$Status, 
                              n.fold = 5, n.iter = 1)                             </code></pre>
<pre><code>## 
## 
## ############################################################### 
##  STARTING selbal.cv FUNCTION 
## ###############################################################
## 
## #-------------------------------------------------------------# 
## # ZERO REPLACEMENT . . .</code></pre>
<pre><code>## Loading required package: MASS</code></pre>
<pre><code>## 
## Attaching package: &#39;MASS&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     select</code></pre>
<pre><code>## Loading required package: NADA</code></pre>
<pre><code>## 
## Attaching package: &#39;NADA&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:IRanges&#39;:
## 
##     cor</code></pre>
<pre><code>## The following object is masked from &#39;package:S4Vectors&#39;:
## 
##     cor</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     cor</code></pre>
<pre><code>## Loading required package: truncnorm</code></pre>
<pre><code>## Loading required package: miscF</code></pre>
<pre><code>## Loading required package: R2jags</code></pre>
<pre><code>## Loading required package: rjags</code></pre>
<pre><code>## Loading required package: coda</code></pre>
<pre><code>## Warning: package &#39;coda&#39; was built under R version 3.6.1</code></pre>
<pre><code>## Linked to JAGS 4.3.0</code></pre>
<pre><code>## Loaded modules: basemod,bugs</code></pre>
<pre><code>## 
## Attaching package: &#39;R2jags&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:coda&#39;:
## 
##     traceplot</code></pre>
<pre><code>## 
## Attaching package: &#39;miscF&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Hmisc&#39;:
## 
##     rMultinom</code></pre>
<pre><code>## 
## , . . . FINISHED. 
## #-------------------------------------------------------------#
## 
## #-------------------------------------------------------------# 
## # Starting the cross - validation procedure . . .</code></pre>
<pre><code>## Warning in e$fun(obj, substitute(ex), parent.frame(), e$data): already
## exporting variable(s): logit.acc</code></pre>
<pre><code>## 
##  . . . finished. 
## #-------------------------------------------------------------# 
## ###############################################################
## 
##  The optimal number of variables is: 2</code></pre>
<pre><code>## Setting levels: control = Control, case = Chronic Fatigue</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<pre><code>## Setting levels: control = Control, case = Chronic Fatigue</code></pre>
<pre><code>## Setting direction: controls &lt; cases</code></pre>
<pre><code>## 
## Attaching package: &#39;gridExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:Biobase&#39;:
## 
##     combine</code></pre>
<pre><code>## The following object is masked from &#39;package:BiocGenerics&#39;:
## 
##     combine</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine</code></pre>
<pre><code>## 
## 
## ############################################################### 
##  . . . FINISHED. 
## ###############################################################</code></pre>
<pre class="r"><code>#plot/print results
cv_sebal$accuracy.nvar</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/selbal-1.png" width="1344" style="display: block; margin: auto;" /></p>
<pre class="r"><code>plot.new()
grid.draw(cv_sebal$global.plot)</code></pre>
<p><img src="/post/2019-07-28-introduction-to-the-statistical-analysis-of-microbiome-data-in-r_files/figure-html/selbal-2.png" width="1344" style="display: block; margin: auto;" /></p>
<p>Here we can see that the cross-validation selected the two balance object as having “among” the best rank-discrimination. It selected the balance with erysipelotrichaceae in the numerator and bifidobacteriaceae in the denominator. So a higher relative abundance of erysipelotrichaceae to bifidobacteriaceae was among the most informative balances. The AUC was 0.77, but as low as AUC = 0.68 with 1 repeat of 5 fold cross-validation.</p>
<p><strong>Give the model a try on the full ps object on your own.</strong> It should run in ~5 min on a standard laptop. <em>How does the performance compare? Would you expect these results to be as reproducible as the GLM we fit? Why?</em></p>
<p><br></p>
</div>
<div id="that-concludes-this-session." class="section level1">
<h1>That concludes this session.</h1>
</div>

    </div>

    

<div class="article-tags">
  
  <a class="badge badge-light" href="/tags/microbiome/">Microbiome</a>
  
  <a class="badge badge-light" href="/tags/r/">R</a>
  
  <a class="badge badge-light" href="/tags/data-analysis/">Data Analysis</a>
  
</div>



    
      








  





  
  
  
    
  
  
  <div class="media author-card" itemscope itemtype="http://schema.org/Person">
    
      
      <img class="portrait mr-3" src="/authors/admin/avatar_hu87de4e6533f526eb4329470784cb7712_907390_250x250_fill_q90_lanczos_center.jpg" itemprop="image" alt="Avatar">
    

    <div class="media-body">
      <h5 class="card-title" itemprop="name"><a href="/">Nicholas Ollberding</a></h5>
      <h6 class="card-subtitle">Associate Professor of Pediatrics and Nutrition</h6>
      
      <ul class="network-icon" aria-hidden="true">
        
          
          
          
            
          
          
          
          
          
          <li>
            <a itemprop="sameAs" href="mailto:nicholas.ollberding@cchmc.org" >
              <i class="fas fa-envelope"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://twitter.com/Nick10243" target="_blank" rel="noopener">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://scholar.google.com/citations?hl=en&amp;user=k9mLyI0AAAAJ" target="_blank" rel="noopener">
              <i class="ai ai-google-scholar"></i>
            </a>
          </li>
        
          
          
          
            
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://github.com/Nick243" target="_blank" rel="noopener">
              <i class="fab fa-github"></i>
            </a>
          </li>
        
          
          
          
          
          
          
          
            
          
          <li>
            <a itemprop="sameAs" href="https://www.researchgate.net/profile/Nicholas_Ollberding" target="_blank" rel="noopener">
              <i class="ai ai-researchgate"></i>
            </a>
          </li>
        
      </ul>
    </div>
  </div>



      
      
      <div class="article-widget">
        <div class="hr-light"></div>
        <h3>Related</h3>
        <ul>
          
          <li><a href="/post/introduction-to-phyloseq/">Introduction to Phyloseq</a></li>
          
          <li><a href="/talk/into-mb-stats/">Introduction to Microbiome Data Analysis </a></li>
          
          <li><a href="/talk/test-talk/">Introduction to Denoising Amplicon Sequence Data in R</a></li>
          
          <li><a href="/talk/dhc/">Recent Advancements in the Statistical Analysis of Microbial Metagenomic Sequence Data</a></li>
          
          <li><a href="/talk/cchmc_rug/">An Introduction to the Harrell“verse”: Predictive Modeling using the Hmisc and rms Packages</a></li>
          
        </ul>
      </div>
      
    

    

    


  </div>
</article>

      

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/highlight.min.js" integrity="sha256-aYTdUrn6Ow1DDgh5JTc3aDGnnju48y/1c8s1dgkYPQ8=" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/r.min.js"></script>
        
      

      
      
    

    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.2.0/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin="anonymous"></script>
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    
    
    
    
    
    
    
      
    
    
    
    
    <script src="/js/academic.min.ac3764a0b2acc1c82ace08e756adafc1.js"></script>

    






  
  <div class="container">
    <footer class="site-footer">
  

  <p class="powered-by">
    

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

  </div>
  

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

</body>
</html>
